services:
  demomusti-pg-data:
    ports:
      - "${PGSQL_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=dockerf
    volumes:
      - quickcode-demomusti-pg-data:/var/lib/postgresql
  
  demomusti-mysql-data:
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - quickcode-demomusti-mysql-data:/var/lib/mysql
      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=RootDocker!
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=dockerf

  demomusti-sql-data:
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "${SQL_PORT:-5433}:1433"
    volumes:
      - quickcode-demomusti-sql-data:/var/opt/mssql

  demomusti-elasticsearch:
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    deploy:
      resources:
        limits:
          memory: 1GB
    ports:
      - "${ELASTIC_PORT:-9200}:9200"
    volumes:
      - quickcode-demomusti-elasticsearch-data:/usr/share/elasticsearch/data
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -s http://demomusti-elasticsearch:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 10

  demomusti-kibana:
    environment:
      - ELASTICSEARCH_HOSTS=http://demomusti-elasticsearch:9200
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    volumes:
      - quickcode-demomusti-kibana-data:/usr/share/kibana/data
    restart: always
    depends_on:
      - demomusti-elasticsearch

  quickcode-demomusti-gateway-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+
    ports:
      - "${GATEWAY_PORT:-6060}:80"

  quickcode-demomusti-identity-module-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+
      - QUICKCODE_JWT_SECRET_KEY=dRFThZSQbvoClfxhwDNe7UkrA7cCrGjYPnz1iFSYX38Webxj7PT0T5SsOVFld5rx
    ports:
      - "6001:80"


  quickcode-demomusti-candidate-tracking-module-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+
      
    ports:
      - "6002:80"


  quickcode-demomusti-interview-module-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+
      
    ports:
      - "6003:80"


  quickcode-demomusti-training-module-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+
      
    ports:
      - "6004:80"


#[-WEB-]
  quickcode-demomusti-portal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+
      - AZURE_ACCOUNT_NAME=quickcodeblobstorage
      - AZURE_ACCOUNT_KEY=azureAccountKeySecret
      - AZURE_BLOB_CONTAINER_NAME=images
    ports:
      - "${PORTAL_PORT:-6020}:80"
      
  quickcode-demomusti-event-listener-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+
    ports:
      - "${EVENT_LISTENER_PORT:-6100}:80"
      
volumes:
  quickcode-demomusti-pg-data:
    external: false
    
  quickcode-demomusti-mysql-data:
    external: false
    
  quickcode-demomusti-sql-data:
    external: false
    
  quickcode-demomusti-elasticsearch-data:
    external: false
    
  quickcode-demomusti-kibana-data:
    external: false
